description = "Show cookie banner to users from the Netherlands"
tags = ["all"]
bucketBy = "userId"

[[environments.staging.rules]]
key = "1"
segments = "*"
percentage = 100

[[environments.production.rules]]
key = "1"
segments = ["netherlands"]
percentage = 100

[[environments.production.rules]]
key = "2"
segments = "*"
percentage = 0
