description = "Show cookie banner to users from the Netherlands"
tags = [ "all" ]
bucketBy = "userId"

[[rules.staging]]
key = "everyone"
segments = "*"
percentage = 100

[[rules.production]]
key = "nl"
segments = [ "netherlands" ]
percentage = 100

[[rules.production]]
key = "everyone"
segments = "*"
percentage = 0
