name: Checks (windows)

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
      - review_requested

jobs:
  ci:
    name: Checks
    runs-on: windows-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          npm ci

      - name: Build
        run: |
          npm run build

      - name: Lint
        run: |
          (cd examples/example-1 && npx featurevisor lint)

      - name: Test
        run: |
          (cd examples/example-1 && npx featurevisor test)
